services:
  - type: web
    name: mst-backend
    env: java
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/MST-Example-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_HOME
        value: "/opt/render/project/.java"
      - key: MAVEN_HOME
        value: "/opt/render/project/.m2"